---
title: "Plan for Final Analytical Projects"
author: ""
date: \today
fontsize: 11pt
linestretch: "1"
indent: false
format:
  pdf:
    extra_dependencies: "subfig"
    keep-tex: false
    number-sections: true
    shift-heading-level-by: 0
    reference-links: true
    reference-location: document
    reference-section-title: "References"
    toc: false
    pdf-engine: "xelatex"
---

Write a data analytical project of **no more than 4,000 words** (excluding references and appendix).

\vspace{0.3cm}

The project should consider the following elements, but should be written as an essay. You can use subheadings if you wish.

\vspace{0.3cm}

1. A **title** of your project.

\vspace{0.3cm}

2. An **introduction**, which should include: 

    - A clear, concise statement of the research question;
  
    - A discussion, accessible to general social researchers, of why your question is interesting (and important). If your study has attractive normative implications, make the most of them here. If it challenges an existing literature or widely accepted theory, say so here. 
  
    - If possible, a simple summary of your proposed answer to the research question that makes clear WHY you expect what you do (even if the explanation of why is included in prior research).

\vspace{0.3cm}

3. A short **literature review** covering only the literatures from which your **hypotheses** are drawn. Be ruthlessly concise in this section. No one reviewing a research proposal wants to read the intellectual history of your subfield. If you are testing implications of the argument described above rather than the argument itself, explain how and why the argument leads to each hypothesis.

\vspace{0.3cm}

4. If you are testing implications of the argument described above rather than the argument itself, explain how and why the argument leads to each hypothesis.

\vspace{0.3cm}

5. **Data and methods**:

    - Explain **operationalization** -- in other words, explain how you will "measure" the outcome you want to explain and the causes or predictors (i.e., explanatory variables) you think are important (including those necessary to test rival arguments), and how you will assess relationships between them. Identify what evidence (that is, what specific facts) you will need in order to decide whether your argument or one of the rivals better explains the outcome you want to explain.

    - Describe in some detail where you have found the data you need (e.g., World Values Survey). Include in this section information about where evidence is located and what arrangements you have made for using it.
    
    - Discuss the ways you propose to use the evidence to assess various arguments. If you plan to use statistics, discuss problems with endogeneity and other challenges that you will face, but focus on substance, not merely the names of statistical models.

\vspace{0.3cm}

6. **Summary** and **discussion** of your main findings.

\vspace{0.3cm}

7. A **concluding section** to discuss briefly theoretical and/or policy implications of your research findings: What do you expect this study to add to our understanding of some broader theoretical question? If the study comes out the way you expect, what will its policy implications (if any) be? What you say here relates back to the introduction in which you described why your research question is interesting.
