---
title: "Reading Questions"
author: ""
date: \today
fontsize: 12pt
linestretch: "1"
indent: false
format:
  pdf:
    extra_dependencies: "subfig"
    keep-tex: false
    number-sections: true
    shift-heading-level-by: 0
    reference-links: true
    reference-location: document
    reference-section-title: "References"
    toc: false
    pdf-engine: "xelatex"
---

We will use the following article to discuss the key elements of a data analytical project.

\vspace{0.3cm}

**Carlitz, Ruth. 2017. "Money Flows, Water Trickles: Understanding Patterns of Decentralized Water Provision in Tanzania." *World Developmen 93*: 16-30.**

\vspace{0.3cm}

For our discussion, you only have to read pp. 16-20 -- that is, till the end of Section 4(c). When you read Carlitz (2017), try your best to think through the following questions:

\vspace{0.3cm}

1. What is her primary "empirical" question (i.e., a research question that can be tested given the data she has collected)? What is the broad theoretical concern that lies behind it (i.e., why is this research question important or interesting)?

\vspace{0.3cm}

2. What is she trying to observe in the data (or, what are her "hypotheses")? 

\vspace{0.3cm}

3. Where did she get the data? What are the key dependent and independent (or explanatory) variables? How did she justify the inclusion of these variables in her multiple regression model?